export const defaultValues = {
    type: "",
    priority: "",
    moderators_exempt: false,
    send_comment: false,
    comment_stickied: false,
    comment_locked: false,
    comment: "",
    send_message: false,
    message_subject: "",
    message: "",
    send_modmail: false,
    modmail_subject: "",
    modmail: "",
    perform_action: false,
    action: false,
    action_reason: false,
    set_flair: false,
    overwrite_flair: false,
    set_sticky: false,
    set_nsfw: false,
    set_spoiler: false,
    set_contest_mode: false,
    set_original_content: false,
    set_suggested_sort: false,
    set_locked: false,
    report_reason: false
};